### ISSUE TITLE
Mondrian Example

### ISSUE THREAD

**Issue by OutBush** [benchmarko/CPCBasicApps#1]
I'm not complaining, but the Modrian Example was written by me, even though SRS played a role, but based on the video 'The Joys of Programming' there were problems with the original QBASIC example, which had lines running up and down the screen, which Modrian art doesn't do, when I looked at some of the examples on the Net. So I produce something that drew squares onscreen of various sizes, and looked for areas around the edges of the squares to run lines from to prevent 'L' like shapes occuring and then used my own FILL routine compatable on all systems.

**Comment by benchmarko** [comment]
Thanks for pointing on this. It seems that I haven't read the cpcwiki thread carefully enough. Your version is a great improvement with new code indeed. I've changed the copyright notice.
https://github.com/benchmarko/CPCBasicApps#mondrian
https://benchmarko.github.io/CPCBasic/cpcbasic.html?database=apps&example=demo/mondrian
